### ISSUE TITLE
Integration fails to start after update

### ISSUE THREAD

**Issue by bmurph213** [bdunn44/hass-jellyfish-lighting#29]
Jellyfish Integration version 1.2.0
HA 
Core 2024.10.3
Supervisor 2024.10.2
OS 13.2
Frontend 20241002.3

Integration fails to start after upgrading to v2024.10.3

Debug
2024-10-20 08:22:37.965 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Home (JellyFish-CBE3.local) for jellyfish_lighting
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/jellyfish_lighting/__init__.py", line 52, in async_setup_entry
    entry.title = f"{client.name} ({client.hostname})"
    ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in __setattr__
    raise AttributeError(
AttributeError: title cannot be changed directly, use async_update_entry instead

Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 7:45:14 AM (2 occurrences)
Last logged: 4:55:40 PM

Error setting up entry Home (JellyFish-CBE3.local) for jellyfish_lighting
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/jellyfish_lighting/__init__.py", line 52, in async_setup_entry
    entry.title = f"{client.name} ({client.hostname})"
    ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in __setattr__
    raise AttributeError(
AttributeError: title cannot be changed directly, use async_update_entry instead

**Comment by bdunn44** [comment]
Hi there! This is due to a change in Home Assistant's code that has been addressed already. Please upgrade to the latest version of the integration (1.3.1) and feel free to reopen if that doesn't fix it for you.
